Se agrego funcion datos
ITIC-ITESME/juego-IsmaelTecnm pull request #1
Opened 2021-11-09 19:18 UTC by IsmaelTecnm

Se agrego un nuevo juego de dados utilizando el modulo random

2021-11-11 02:17 UTC, ingrafaelcr commented
Se encuentra en verificación la funcionalidad que enviaste.

2021-11-11 20:24 UTC, IsmaelTecnm commented
Enterado, estoy a espera, por cualquier duda

2021-11-11 20:40 UTC, ingrafaelcr requested changes
Se verificaron las nueva función de dados, esta todo correcto. solo falta agregar datos de los juegos en el archivo README del proyecto.

2021-11-11 23:36 UTC, IsmaelTecnm commented
Enterado, modificaré el README

2021-11-12 01:12 UTC, ingrafaelcr approved these changes
Excelente se enviara a merge.

2021-11-12 01:13 UTC, merged